// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_workflow_status_summary

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func WorkflowStatusSummaryDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"fields": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "a comma-separated list of resource fields to fetch/return.  If unspecified, all fields are fetched.  If empty, only key-fields are fetched.",
				MarkdownDescription: "a comma-separated list of resource fields to fetch/return.  If unspecified, all fields are fetched.  If empty, only key-fields are fetched.",
			},
			"filter": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "an EQL \"where\" expression that will be used to filter the set of resources returned.",
				MarkdownDescription: "an EQL \"where\" expression that will be used to filter the set of resources returned.",
			},
			"label_selector": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "a label selector string to filter the results based on CR labels",
				MarkdownDescription: "a label selector string to filter the results based on CR labels",
			},
			"labelselector": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Deprecated: a label selector string to filter the results based on CR labels",
				MarkdownDescription: "Deprecated: a label selector string to filter the results based on CR labels",
			},
			"workflow_status_summary": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"creation_time": schema.StringAttribute{
							Computed: true,
						},
						"group": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"kind": schema.StringAttribute{
							Computed: true,
						},
						"last_update": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"namespace": schema.StringAttribute{
							Computed: true,
						},
						"parent": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"group": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"kind": schema.StringAttribute{
									Computed: true,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
								"namespace": schema.StringAttribute{
									Computed: true,
								},
								"version": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: ParentType{
								ObjectType: types.ObjectType{
									AttrTypes: ParentValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"root_workflow": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"group": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"kind": schema.StringAttribute{
									Computed: true,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
								"namespace": schema.StringAttribute{
									Computed: true,
								},
								"version": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: RootWorkflowType{
								ObjectType: types.ObjectType{
									AttrTypes: RootWorkflowValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"state": schema.StringAttribute{
							Computed: true,
						},
						"username": schema.StringAttribute{
							Computed: true,
						},
						"version": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: WorkflowStatusSummaryType{
						ObjectType: types.ObjectType{
							AttrTypes: WorkflowStatusSummaryValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type WorkflowStatusSummaryModel struct {
	Fields                types.String `tfsdk:"fields"`
	Filter                types.String `tfsdk:"filter"`
	LabelSelector         types.String `tfsdk:"label_selector"`
	Labelselector         types.String `tfsdk:"labelselector"`
	WorkflowStatusSummary types.Set    `tfsdk:"workflow_status_summary"`
}

var _ basetypes.ObjectTypable = WorkflowStatusSummaryType{}

type WorkflowStatusSummaryType struct {
	basetypes.ObjectType
}

func (t WorkflowStatusSummaryType) Equal(o attr.Type) bool {
	other, ok := o.(WorkflowStatusSummaryType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t WorkflowStatusSummaryType) String() string {
	return "WorkflowStatusSummaryType"
}

func (t WorkflowStatusSummaryType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	creationTimeAttribute, ok := attributes["creation_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`creation_time is missing from object`)

		return nil, diags
	}

	creationTimeVal, ok := creationTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`creation_time expected to be basetypes.StringValue, was: %T`, creationTimeAttribute))
	}

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return nil, diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return nil, diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	lastUpdateAttribute, ok := attributes["last_update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_update is missing from object`)

		return nil, diags
	}

	lastUpdateVal, ok := lastUpdateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_update expected to be basetypes.StringValue, was: %T`, lastUpdateAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	namespaceAttribute, ok := attributes["namespace"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`namespace is missing from object`)

		return nil, diags
	}

	namespaceVal, ok := namespaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`namespace expected to be basetypes.StringValue, was: %T`, namespaceAttribute))
	}

	parentAttribute, ok := attributes["parent"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parent is missing from object`)

		return nil, diags
	}

	parentVal, ok := parentAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parent expected to be basetypes.ObjectValue, was: %T`, parentAttribute))
	}

	rootWorkflowAttribute, ok := attributes["root_workflow"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`root_workflow is missing from object`)

		return nil, diags
	}

	rootWorkflowVal, ok := rootWorkflowAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`root_workflow expected to be basetypes.ObjectValue, was: %T`, rootWorkflowAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return nil, diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return WorkflowStatusSummaryValue{
		CreationTime: creationTimeVal,
		Group:        groupVal,
		Id:           idVal,
		Kind:         kindVal,
		LastUpdate:   lastUpdateVal,
		Name:         nameVal,
		Namespace:    namespaceVal,
		Parent:       parentVal,
		RootWorkflow: rootWorkflowVal,
		State:        stateVal,
		Username:     usernameVal,
		Version:      versionVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewWorkflowStatusSummaryValueNull() WorkflowStatusSummaryValue {
	return WorkflowStatusSummaryValue{
		state: attr.ValueStateNull,
	}
}

func NewWorkflowStatusSummaryValueUnknown() WorkflowStatusSummaryValue {
	return WorkflowStatusSummaryValue{
		state: attr.ValueStateUnknown,
	}
}

func NewWorkflowStatusSummaryValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (WorkflowStatusSummaryValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing WorkflowStatusSummaryValue Attribute Value",
				"While creating a WorkflowStatusSummaryValue value, a missing attribute value was detected. "+
					"A WorkflowStatusSummaryValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("WorkflowStatusSummaryValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid WorkflowStatusSummaryValue Attribute Type",
				"While creating a WorkflowStatusSummaryValue value, an invalid attribute value was detected. "+
					"A WorkflowStatusSummaryValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("WorkflowStatusSummaryValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("WorkflowStatusSummaryValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra WorkflowStatusSummaryValue Attribute Value",
				"While creating a WorkflowStatusSummaryValue value, an extra attribute value was detected. "+
					"A WorkflowStatusSummaryValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra WorkflowStatusSummaryValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	creationTimeAttribute, ok := attributes["creation_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`creation_time is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	creationTimeVal, ok := creationTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`creation_time expected to be basetypes.StringValue, was: %T`, creationTimeAttribute))
	}

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	lastUpdateAttribute, ok := attributes["last_update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_update is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	lastUpdateVal, ok := lastUpdateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_update expected to be basetypes.StringValue, was: %T`, lastUpdateAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	namespaceAttribute, ok := attributes["namespace"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`namespace is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	namespaceVal, ok := namespaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`namespace expected to be basetypes.StringValue, was: %T`, namespaceAttribute))
	}

	parentAttribute, ok := attributes["parent"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parent is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	parentVal, ok := parentAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parent expected to be basetypes.ObjectValue, was: %T`, parentAttribute))
	}

	rootWorkflowAttribute, ok := attributes["root_workflow"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`root_workflow is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	rootWorkflowVal, ok := rootWorkflowAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`root_workflow expected to be basetypes.ObjectValue, was: %T`, rootWorkflowAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return NewWorkflowStatusSummaryValueUnknown(), diags
	}

	return WorkflowStatusSummaryValue{
		CreationTime: creationTimeVal,
		Group:        groupVal,
		Id:           idVal,
		Kind:         kindVal,
		LastUpdate:   lastUpdateVal,
		Name:         nameVal,
		Namespace:    namespaceVal,
		Parent:       parentVal,
		RootWorkflow: rootWorkflowVal,
		State:        stateVal,
		Username:     usernameVal,
		Version:      versionVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewWorkflowStatusSummaryValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) WorkflowStatusSummaryValue {
	object, diags := NewWorkflowStatusSummaryValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewWorkflowStatusSummaryValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t WorkflowStatusSummaryType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewWorkflowStatusSummaryValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewWorkflowStatusSummaryValueUnknown(), nil
	}

	if in.IsNull() {
		return NewWorkflowStatusSummaryValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewWorkflowStatusSummaryValueMust(WorkflowStatusSummaryValue{}.AttributeTypes(ctx), attributes), nil
}

func (t WorkflowStatusSummaryType) ValueType(ctx context.Context) attr.Value {
	return WorkflowStatusSummaryValue{}
}

var _ basetypes.ObjectValuable = WorkflowStatusSummaryValue{}

type WorkflowStatusSummaryValue struct {
	CreationTime basetypes.StringValue `tfsdk:"creation_time"`
	Group        basetypes.StringValue `tfsdk:"group"`
	Id           basetypes.Int64Value  `tfsdk:"id"`
	Kind         basetypes.StringValue `tfsdk:"kind"`
	LastUpdate   basetypes.StringValue `tfsdk:"last_update"`
	Name         basetypes.StringValue `tfsdk:"name"`
	Namespace    basetypes.StringValue `tfsdk:"namespace"`
	Parent       basetypes.ObjectValue `tfsdk:"parent"`
	RootWorkflow basetypes.ObjectValue `tfsdk:"root_workflow"`
	State        basetypes.StringValue `tfsdk:"state"`
	Username     basetypes.StringValue `tfsdk:"username"`
	Version      basetypes.StringValue `tfsdk:"version"`
	state        attr.ValueState
}

func (v WorkflowStatusSummaryValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["creation_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["group"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_update"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["namespace"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["parent"] = basetypes.ObjectType{
		AttrTypes: ParentValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["root_workflow"] = basetypes.ObjectType{
		AttrTypes: RootWorkflowValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.CreationTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["creation_time"] = val

		val, err = v.Group.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Kind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kind"] = val

		val, err = v.LastUpdate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_update"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Namespace.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["namespace"] = val

		val, err = v.Parent.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["parent"] = val

		val, err = v.RootWorkflow.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["root_workflow"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		val, err = v.Version.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v WorkflowStatusSummaryValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v WorkflowStatusSummaryValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v WorkflowStatusSummaryValue) String() string {
	return "WorkflowStatusSummaryValue"
}

func (v WorkflowStatusSummaryValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var parent basetypes.ObjectValue

	if v.Parent.IsNull() {
		parent = types.ObjectNull(
			ParentValue{}.AttributeTypes(ctx),
		)
	}

	if v.Parent.IsUnknown() {
		parent = types.ObjectUnknown(
			ParentValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Parent.IsNull() && !v.Parent.IsUnknown() {
		parent = types.ObjectValueMust(
			ParentValue{}.AttributeTypes(ctx),
			v.Parent.Attributes(),
		)
	}

	var rootWorkflow basetypes.ObjectValue

	if v.RootWorkflow.IsNull() {
		rootWorkflow = types.ObjectNull(
			RootWorkflowValue{}.AttributeTypes(ctx),
		)
	}

	if v.RootWorkflow.IsUnknown() {
		rootWorkflow = types.ObjectUnknown(
			RootWorkflowValue{}.AttributeTypes(ctx),
		)
	}

	if !v.RootWorkflow.IsNull() && !v.RootWorkflow.IsUnknown() {
		rootWorkflow = types.ObjectValueMust(
			RootWorkflowValue{}.AttributeTypes(ctx),
			v.RootWorkflow.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"creation_time": basetypes.StringType{},
		"group":         basetypes.StringType{},
		"id":            basetypes.Int64Type{},
		"kind":          basetypes.StringType{},
		"last_update":   basetypes.StringType{},
		"name":          basetypes.StringType{},
		"namespace":     basetypes.StringType{},
		"parent": basetypes.ObjectType{
			AttrTypes: ParentValue{}.AttributeTypes(ctx),
		},
		"root_workflow": basetypes.ObjectType{
			AttrTypes: RootWorkflowValue{}.AttributeTypes(ctx),
		},
		"state":    basetypes.StringType{},
		"username": basetypes.StringType{},
		"version":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"creation_time": v.CreationTime,
			"group":         v.Group,
			"id":            v.Id,
			"kind":          v.Kind,
			"last_update":   v.LastUpdate,
			"name":          v.Name,
			"namespace":     v.Namespace,
			"parent":        parent,
			"root_workflow": rootWorkflow,
			"state":         v.State,
			"username":      v.Username,
			"version":       v.Version,
		})

	return objVal, diags
}

func (v WorkflowStatusSummaryValue) Equal(o attr.Value) bool {
	other, ok := o.(WorkflowStatusSummaryValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreationTime.Equal(other.CreationTime) {
		return false
	}

	if !v.Group.Equal(other.Group) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Kind.Equal(other.Kind) {
		return false
	}

	if !v.LastUpdate.Equal(other.LastUpdate) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Namespace.Equal(other.Namespace) {
		return false
	}

	if !v.Parent.Equal(other.Parent) {
		return false
	}

	if !v.RootWorkflow.Equal(other.RootWorkflow) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	if !v.Version.Equal(other.Version) {
		return false
	}

	return true
}

func (v WorkflowStatusSummaryValue) Type(ctx context.Context) attr.Type {
	return WorkflowStatusSummaryType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v WorkflowStatusSummaryValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"creation_time": basetypes.StringType{},
		"group":         basetypes.StringType{},
		"id":            basetypes.Int64Type{},
		"kind":          basetypes.StringType{},
		"last_update":   basetypes.StringType{},
		"name":          basetypes.StringType{},
		"namespace":     basetypes.StringType{},
		"parent": basetypes.ObjectType{
			AttrTypes: ParentValue{}.AttributeTypes(ctx),
		},
		"root_workflow": basetypes.ObjectType{
			AttrTypes: RootWorkflowValue{}.AttributeTypes(ctx),
		},
		"state":    basetypes.StringType{},
		"username": basetypes.StringType{},
		"version":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ParentType{}

type ParentType struct {
	basetypes.ObjectType
}

func (t ParentType) Equal(o attr.Type) bool {
	other, ok := o.(ParentType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ParentType) String() string {
	return "ParentType"
}

func (t ParentType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return nil, diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return nil, diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	namespaceAttribute, ok := attributes["namespace"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`namespace is missing from object`)

		return nil, diags
	}

	namespaceVal, ok := namespaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`namespace expected to be basetypes.StringValue, was: %T`, namespaceAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return nil, diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ParentValue{
		Group:     groupVal,
		Id:        idVal,
		Kind:      kindVal,
		Name:      nameVal,
		Namespace: namespaceVal,
		Version:   versionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewParentValueNull() ParentValue {
	return ParentValue{
		state: attr.ValueStateNull,
	}
}

func NewParentValueUnknown() ParentValue {
	return ParentValue{
		state: attr.ValueStateUnknown,
	}
}

func NewParentValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ParentValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ParentValue Attribute Value",
				"While creating a ParentValue value, a missing attribute value was detected. "+
					"A ParentValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ParentValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ParentValue Attribute Type",
				"While creating a ParentValue value, an invalid attribute value was detected. "+
					"A ParentValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ParentValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ParentValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ParentValue Attribute Value",
				"While creating a ParentValue value, an extra attribute value was detected. "+
					"A ParentValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ParentValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewParentValueUnknown(), diags
	}

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return NewParentValueUnknown(), diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewParentValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return NewParentValueUnknown(), diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewParentValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	namespaceAttribute, ok := attributes["namespace"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`namespace is missing from object`)

		return NewParentValueUnknown(), diags
	}

	namespaceVal, ok := namespaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`namespace expected to be basetypes.StringValue, was: %T`, namespaceAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return NewParentValueUnknown(), diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return NewParentValueUnknown(), diags
	}

	return ParentValue{
		Group:     groupVal,
		Id:        idVal,
		Kind:      kindVal,
		Name:      nameVal,
		Namespace: namespaceVal,
		Version:   versionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewParentValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ParentValue {
	object, diags := NewParentValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewParentValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ParentType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewParentValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewParentValueUnknown(), nil
	}

	if in.IsNull() {
		return NewParentValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewParentValueMust(ParentValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ParentType) ValueType(ctx context.Context) attr.Value {
	return ParentValue{}
}

var _ basetypes.ObjectValuable = ParentValue{}

type ParentValue struct {
	Group     basetypes.StringValue `tfsdk:"group"`
	Id        basetypes.Int64Value  `tfsdk:"id"`
	Kind      basetypes.StringValue `tfsdk:"kind"`
	Name      basetypes.StringValue `tfsdk:"name"`
	Namespace basetypes.StringValue `tfsdk:"namespace"`
	Version   basetypes.StringValue `tfsdk:"version"`
	state     attr.ValueState
}

func (v ParentValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["group"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["namespace"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Group.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Kind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kind"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Namespace.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["namespace"] = val

		val, err = v.Version.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ParentValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ParentValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ParentValue) String() string {
	return "ParentValue"
}

func (v ParentValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"group":     basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"kind":      basetypes.StringType{},
		"name":      basetypes.StringType{},
		"namespace": basetypes.StringType{},
		"version":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"group":     v.Group,
			"id":        v.Id,
			"kind":      v.Kind,
			"name":      v.Name,
			"namespace": v.Namespace,
			"version":   v.Version,
		})

	return objVal, diags
}

func (v ParentValue) Equal(o attr.Value) bool {
	other, ok := o.(ParentValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Group.Equal(other.Group) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Kind.Equal(other.Kind) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Namespace.Equal(other.Namespace) {
		return false
	}

	if !v.Version.Equal(other.Version) {
		return false
	}

	return true
}

func (v ParentValue) Type(ctx context.Context) attr.Type {
	return ParentType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ParentValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"group":     basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"kind":      basetypes.StringType{},
		"name":      basetypes.StringType{},
		"namespace": basetypes.StringType{},
		"version":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = RootWorkflowType{}

type RootWorkflowType struct {
	basetypes.ObjectType
}

func (t RootWorkflowType) Equal(o attr.Type) bool {
	other, ok := o.(RootWorkflowType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RootWorkflowType) String() string {
	return "RootWorkflowType"
}

func (t RootWorkflowType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return nil, diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return nil, diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	namespaceAttribute, ok := attributes["namespace"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`namespace is missing from object`)

		return nil, diags
	}

	namespaceVal, ok := namespaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`namespace expected to be basetypes.StringValue, was: %T`, namespaceAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return nil, diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RootWorkflowValue{
		Group:     groupVal,
		Id:        idVal,
		Kind:      kindVal,
		Name:      nameVal,
		Namespace: namespaceVal,
		Version:   versionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewRootWorkflowValueNull() RootWorkflowValue {
	return RootWorkflowValue{
		state: attr.ValueStateNull,
	}
}

func NewRootWorkflowValueUnknown() RootWorkflowValue {
	return RootWorkflowValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRootWorkflowValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RootWorkflowValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RootWorkflowValue Attribute Value",
				"While creating a RootWorkflowValue value, a missing attribute value was detected. "+
					"A RootWorkflowValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RootWorkflowValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RootWorkflowValue Attribute Type",
				"While creating a RootWorkflowValue value, an invalid attribute value was detected. "+
					"A RootWorkflowValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RootWorkflowValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RootWorkflowValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RootWorkflowValue Attribute Value",
				"While creating a RootWorkflowValue value, an extra attribute value was detected. "+
					"A RootWorkflowValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RootWorkflowValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRootWorkflowValueUnknown(), diags
	}

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return NewRootWorkflowValueUnknown(), diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewRootWorkflowValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return NewRootWorkflowValueUnknown(), diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewRootWorkflowValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	namespaceAttribute, ok := attributes["namespace"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`namespace is missing from object`)

		return NewRootWorkflowValueUnknown(), diags
	}

	namespaceVal, ok := namespaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`namespace expected to be basetypes.StringValue, was: %T`, namespaceAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return NewRootWorkflowValueUnknown(), diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return NewRootWorkflowValueUnknown(), diags
	}

	return RootWorkflowValue{
		Group:     groupVal,
		Id:        idVal,
		Kind:      kindVal,
		Name:      nameVal,
		Namespace: namespaceVal,
		Version:   versionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewRootWorkflowValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RootWorkflowValue {
	object, diags := NewRootWorkflowValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRootWorkflowValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RootWorkflowType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRootWorkflowValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRootWorkflowValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRootWorkflowValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRootWorkflowValueMust(RootWorkflowValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RootWorkflowType) ValueType(ctx context.Context) attr.Value {
	return RootWorkflowValue{}
}

var _ basetypes.ObjectValuable = RootWorkflowValue{}

type RootWorkflowValue struct {
	Group     basetypes.StringValue `tfsdk:"group"`
	Id        basetypes.Int64Value  `tfsdk:"id"`
	Kind      basetypes.StringValue `tfsdk:"kind"`
	Name      basetypes.StringValue `tfsdk:"name"`
	Namespace basetypes.StringValue `tfsdk:"namespace"`
	Version   basetypes.StringValue `tfsdk:"version"`
	state     attr.ValueState
}

func (v RootWorkflowValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["group"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["namespace"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Group.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Kind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kind"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Namespace.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["namespace"] = val

		val, err = v.Version.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RootWorkflowValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RootWorkflowValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RootWorkflowValue) String() string {
	return "RootWorkflowValue"
}

func (v RootWorkflowValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"group":     basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"kind":      basetypes.StringType{},
		"name":      basetypes.StringType{},
		"namespace": basetypes.StringType{},
		"version":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"group":     v.Group,
			"id":        v.Id,
			"kind":      v.Kind,
			"name":      v.Name,
			"namespace": v.Namespace,
			"version":   v.Version,
		})

	return objVal, diags
}

func (v RootWorkflowValue) Equal(o attr.Value) bool {
	other, ok := o.(RootWorkflowValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Group.Equal(other.Group) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Kind.Equal(other.Kind) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Namespace.Equal(other.Namespace) {
		return false
	}

	if !v.Version.Equal(other.Version) {
		return false
	}

	return true
}

func (v RootWorkflowValue) Type(ctx context.Context) attr.Type {
	return RootWorkflowType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RootWorkflowValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"group":     basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"kind":      basetypes.StringType{},
		"name":      basetypes.StringType{},
		"namespace": basetypes.StringType{},
		"version":   basetypes.StringType{},
	}
}
