// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_workflow_state

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func WorkflowStateDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"running_state": schema.StringAttribute{
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"workflow_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The identifier for the workflow whose state is being requested",
				MarkdownDescription: "The identifier for the workflow whose state is being requested",
			},
		},
	}
}

type WorkflowStateModel struct {
	RunningState types.String `tfsdk:"running_state"`
	State        types.String `tfsdk:"state"`
	WorkflowId   types.Int64  `tfsdk:"workflow_id"`
}
