// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_conversation_history

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ConversationHistoryDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"chat_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the requested chat",
				MarkdownDescription: "The ID of the requested chat",
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Time when the conversation was created",
				MarkdownDescription: "Time when the conversation was created",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Conversation ID",
				MarkdownDescription: "Conversation ID",
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				Description:         "Time when the conversation was last updated",
				MarkdownDescription: "Time when the conversation was last updated",
			},
			"message_count": schema.Int64Attribute{
				Computed:            true,
				Description:         "Number of messages in the conversation",
				MarkdownDescription: "Number of messages in the conversation",
			},
			"messages": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"role": schema.StringAttribute{
							Computed: true,
						},
						"type": schema.Int64Attribute{
							Computed: true,
						},
						"value": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{},
							CustomType: ValueType{
								ObjectType: types.ObjectType{
									AttrTypes: ValueValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "The content of the message returned from ai",
							MarkdownDescription: "The content of the message returned from ai",
						},
					},
					CustomType: MessagesType{
						ObjectType: types.ObjectType{
							AttrTypes: MessagesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "List of messages in the conversation",
				MarkdownDescription: "List of messages in the conversation",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Conversation name",
				MarkdownDescription: "Conversation name",
			},
		},
	}
}

type ConversationHistoryModel struct {
	ChatId       types.String `tfsdk:"chat_id"`
	Created      types.String `tfsdk:"created"`
	Id           types.String `tfsdk:"id"`
	LastUpdated  types.String `tfsdk:"last_updated"`
	MessageCount types.Int64  `tfsdk:"message_count"`
	Messages     types.List   `tfsdk:"messages"`
	Name         types.String `tfsdk:"name"`
}

var _ basetypes.ObjectTypable = MessagesType{}

type MessagesType struct {
	basetypes.ObjectType
}

func (t MessagesType) Equal(o attr.Type) bool {
	other, ok := o.(MessagesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MessagesType) String() string {
	return "MessagesType"
}

func (t MessagesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	roleAttribute, ok := attributes["role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role is missing from object`)

		return nil, diags
	}

	roleVal, ok := roleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role expected to be basetypes.StringValue, was: %T`, roleAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.Int64Value, was: %T`, typeAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.ObjectValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MessagesValue{
		Role:         roleVal,
		MessagesType: typeVal,
		Value:        valueVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewMessagesValueNull() MessagesValue {
	return MessagesValue{
		state: attr.ValueStateNull,
	}
}

func NewMessagesValueUnknown() MessagesValue {
	return MessagesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMessagesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MessagesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MessagesValue Attribute Value",
				"While creating a MessagesValue value, a missing attribute value was detected. "+
					"A MessagesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MessagesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MessagesValue Attribute Type",
				"While creating a MessagesValue value, an invalid attribute value was detected. "+
					"A MessagesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MessagesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MessagesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MessagesValue Attribute Value",
				"While creating a MessagesValue value, an extra attribute value was detected. "+
					"A MessagesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MessagesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMessagesValueUnknown(), diags
	}

	roleAttribute, ok := attributes["role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role is missing from object`)

		return NewMessagesValueUnknown(), diags
	}

	roleVal, ok := roleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role expected to be basetypes.StringValue, was: %T`, roleAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewMessagesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.Int64Value, was: %T`, typeAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewMessagesValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.ObjectValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewMessagesValueUnknown(), diags
	}

	return MessagesValue{
		Role:         roleVal,
		MessagesType: typeVal,
		Value:        valueVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewMessagesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MessagesValue {
	object, diags := NewMessagesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMessagesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MessagesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMessagesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMessagesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMessagesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMessagesValueMust(MessagesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MessagesType) ValueType(ctx context.Context) attr.Value {
	return MessagesValue{}
}

var _ basetypes.ObjectValuable = MessagesValue{}

type MessagesValue struct {
	Role         basetypes.StringValue `tfsdk:"role"`
	MessagesType basetypes.Int64Value  `tfsdk:"type"`
	Value        basetypes.ObjectValue `tfsdk:"value"`
	state        attr.ValueState
}

func (v MessagesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["role"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.ObjectType{
		AttrTypes: ValueValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Role.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role"] = val

		val, err = v.MessagesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MessagesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MessagesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MessagesValue) String() string {
	return "MessagesValue"
}

func (v MessagesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var value basetypes.ObjectValue

	if v.Value.IsNull() {
		value = types.ObjectNull(
			ValueValue{}.AttributeTypes(ctx),
		)
	}

	if v.Value.IsUnknown() {
		value = types.ObjectUnknown(
			ValueValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Value.IsNull() && !v.Value.IsUnknown() {
		value = types.ObjectValueMust(
			ValueValue{}.AttributeTypes(ctx),
			v.Value.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"role": basetypes.StringType{},
		"type": basetypes.Int64Type{},
		"value": basetypes.ObjectType{
			AttrTypes: ValueValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"role":  v.Role,
			"type":  v.MessagesType,
			"value": value,
		})

	return objVal, diags
}

func (v MessagesValue) Equal(o attr.Value) bool {
	other, ok := o.(MessagesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Role.Equal(other.Role) {
		return false
	}

	if !v.MessagesType.Equal(other.MessagesType) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v MessagesValue) Type(ctx context.Context) attr.Type {
	return MessagesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MessagesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"role": basetypes.StringType{},
		"type": basetypes.Int64Type{},
		"value": basetypes.ObjectType{
			AttrTypes: ValueValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = ValueType{}

type ValueType struct {
	basetypes.ObjectType
}

func (t ValueType) Equal(o attr.Type) bool {
	other, ok := o.(ValueType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ValueType) String() string {
	return "ValueType"
}

func (t ValueType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return ValueValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewValueValueNull() ValueValue {
	return ValueValue{
		state: attr.ValueStateNull,
	}
}

func NewValueValueUnknown() ValueValue {
	return ValueValue{
		state: attr.ValueStateUnknown,
	}
}

func NewValueValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ValueValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ValueValue Attribute Value",
				"While creating a ValueValue value, a missing attribute value was detected. "+
					"A ValueValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ValueValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ValueValue Attribute Type",
				"While creating a ValueValue value, an invalid attribute value was detected. "+
					"A ValueValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ValueValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ValueValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ValueValue Attribute Value",
				"While creating a ValueValue value, an extra attribute value was detected. "+
					"A ValueValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ValueValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewValueValueUnknown(), diags
	}

	if diags.HasError() {
		return NewValueValueUnknown(), diags
	}

	return ValueValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewValueValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ValueValue {
	object, diags := NewValueValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewValueValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ValueType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewValueValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewValueValueUnknown(), nil
	}

	if in.IsNull() {
		return NewValueValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewValueValueMust(ValueValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ValueType) ValueType(ctx context.Context) attr.Value {
	return ValueValue{}
}

var _ basetypes.ObjectValuable = ValueValue{}

type ValueValue struct {
	state attr.ValueState
}

func (v ValueValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ValueValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ValueValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ValueValue) String() string {
	return "ValueValue"
}

func (v ValueValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v ValueValue) Equal(o attr.Value) bool {
	other, ok := o.(ValueValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v ValueValue) Type(ctx context.Context) attr.Type {
	return ValueType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ValueValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
