alarm_data:
  - read:
      path: /core/alarm/v2/alarms
      method: GET
  - read:
      path: /core/alarm/v2/alarms/{alarm-name}
      method: GET
  - read:
      path: /core/alarm/v2/namespaces/{nsName}/alarms
      method: GET
  - read:
      path: /core/alarm/v2/namespaces/{nsName}/alarms/{alarm-name}
      method: GET

alarm_history_entry:
  - read:
      path: /core/alarm/v2/alarms/{alarm-name}/history
      method: GET
  - read:
      path: /core/alarm/v2/namespaces/{nsName}/alarms/{alarm-name}/history
      method: GET

alarm_namespace_and_name:
  - update:
      path: /core/alarm/v2/alarms
      method: PUT
  - delete:
      path: /core/alarm/v2/alarms
      method: DELETE
  - update:
      path: /core/alarm/v2/namespaces/{nsName}/alarms
      method: PUT
  - delete:
      path: /core/alarm/v2/namespaces/{nsName}/alarms
      method: DELETE

auth_password_policy:
  - read:
      path: /core/admin/passwordpolicy
      method: GET
  - update:
      path: /core/admin/passwordpolicy
      method: PUT

auth_provider:
  - create:
      path: /core/admin/federationproviders
      method: POST
  - read:
      path: /core/admin/federationproviders/{uuid}
      method: GET
  - update:
      path: /core/admin/federationproviders/{uuid}
      method: PUT

auth_provider_test_params:
  - create:
      path: /core/admin/federationprovidertest
      method: POST

auth_providers:
  - read:
      path: /core/admin/federationproviders
      method: GET

auth_role:
  - create:
      path: /core/admin/namespaces/{namespace}/roles
      method: POST
  - read:
      path: /core/admin/namespaces/{namespace}/roles/{name}
      method: GET
  - update:
      path: /core/admin/namespaces/{namespace}/roles/{name}
      method: PUT
  - create:
      path: /core/admin/roles
      method: POST
  - read:
      path: /core/admin/roles/{name}
      method: GET
  - update:
      path: /core/admin/roles/{name}
      method: PUT

auth_roles:
  - read:
      path: /core/admin/groups/{uuid}/roles
      method: GET
  - read:
      path: /core/admin/namespaces/{namespace}/roles
      method: GET
  - read:
      path: /core/admin/roles
      method: GET

auth_user:
  - create:
      path: /core/admin/users
      method: POST
  - read:
      path: /core/admin/users/{uuid}
      method: GET
  - update:
      path: /core/admin/users/{uuid}
      method: PUT

auth_user_group:
  - create:
      path: /core/admin/groups
      method: POST
  - read:
      path: /core/admin/groups/{uuid}
      method: GET
  - update:
      path: /core/admin/groups/{uuid}
      method: PUT

auth_user_groups:
  - read:
      path: /core/admin/groups
      method: GET

auth_users:
  - read:
      path: /core/admin/users
      method: GET

auto_complete_request:
  - create:
      path: /core/autocomplete/v1/fields
      method: POST
  - create:
      path: /core/autocomplete/v1/gvk
      method: POST
  - create:
      path: /core/autocomplete/v1/gvr
      method: POST
  - create:
      path: /core/autocomplete/v1/labelselector
      method: POST
  - create:
      path: /core/autocomplete/v1/table
      method: POST
  - create:
      path: /core/autocomplete/v1/where
      method: POST

check_access_request:
  - create:
      path: /core/access/v1/checkAccess
      method: POST

conversation_history:
  - read:
      path: /core/chat/v1/chats/{chatId}
      method: GET

conversation_info:
  - update:
      path: /core/chat/v1/chats/{chatId}
      method: PUT

conversation_list:
  - read:
      path: /core/chat/v1/chats
      method: GET

credentials:
  - update:
      path: /core/admin/users/{uuid}/resetpassword
      method: PUT

get_label_completion_request:
  - create:
      path: /core/autocomplete/v1/labels
      method: POST

group_i_ds:
  - create:
      path: /core/admin/users/{uuid}/groups
      method: POST
  - update:
      path: /core/admin/users/{uuid}/groups
      method: PUT
  - delete:
      path: /core/admin/users/{uuid}/groups
      method: DELETE

health:
  - read:
      path: /core/about/health
      method: GET

namespace_get_response:
  - read:
      path: /core/access/v1/namespaces
      method: GET

node_config_response:
  - read:
      path: /core/nodeconfig/v2/namespaces/{nsName}/nodes/{nodeName}
      method: GET

overlay:
  - read:
      path: /core/topology/v1/{topologyName}/overlay/{overlayName}
      method: GET

overlays:
  - read:
      path: /core/topology/v1/{topologyName}/overlay
      method: GET

query_completion_response:
  - read:
      path: /core/query/v1/eql/autocomplete
      method: GET

query_convert_request:
  - create:
      path: /core/query/v1/convert
      method: POST

query_response:
  - read:
      path: /core/query/v1
      method: GET
  - read:
      path: /core/query/v1/eql
      method: GET
  - read:
      path: /core/query/v1/nql
      method: GET

store_app_installed_settings:
  - read:
      path: /core/store/v1/installedsettings/app/{appId}
      method: GET

store_app_manifest:
  - read:
      path: /core/store/v1/manifest/catalog/{catalog}/app/{appId}
      method: GET

store_app_requirements_graph:
  - read:
      path: /core/store/v1/requirementsgraph/catalog/{catalog}/app/{appId}
      method: GET

store_app_settings_definition:
  - read:
      path: /core/store/v1/appsettingsdefinition/catalog/{catalog}/app/{appId}
      method: GET

store_app_summary:
  - read:
      path: /core/store/v1/appsummaries/app/{appId}
      method: GET

store_app_summary_list:
  - read:
      path: /core/store/v1/appsummaries
      method: GET

store_app_version_list:
  - read:
      path: /core/store/v1/versions/app/{appId}
      method: GET

store_category_list:
  - read:
      path: /core/store/v1/categories
      method: GET

topo_state_request:
  - create:
      path: /core/topology/v1/{topologyName}/state
      method: POST

topologies:
  - read:
      path: /core/topology/v1
      method: GET

topology:
  - read:
      path: /core/topology/v1/{topologyName}
      method: GET

topology_grouping_instance:
  - read:
      path: /core/topology/v1/{topologyName}/groupings/{groupingName}
      method: GET

topology_groupings_list:
  - read:
      path: /core/topology/v1/{topologyName}/groupings
      method: GET

transaction:
  - create:
      path: /core/transaction/v2
      method: POST

transaction_cr:
  - create:
      path: /core/transaction/v2/validate
      method: POST

transaction_execution_result:
  - read:
      path: /core/transaction/v2/result/execution/{transactionId}
      method: GET

transaction_result_input_resources:
  - read:
      path: /core/transaction/v2/result/inputresources/{transactionId}
      method: GET

transaction_result_object:
  - read:
      path: /core/transaction/v2/result/diffs/nodecfg/{transactionId}
      method: GET
  - read:
      path: /core/transaction/v2/result/diffs/resource/{transactionId}
      method: GET

transaction_revert_restore_request:
  - create:
      path: /core/transaction/v2/restore/{transactionId}
      method: POST
  - create:
      path: /core/transaction/v2/revert/{transactionId}
      method: POST

transaction_state:
  - read:
      path: /core/transaction/v2/state/{transactionId}
      method: GET

transaction_summary_result:
  - read:
      path: /core/transaction/v2/result/summary/{transactionId}
      method: GET

transaction_summary_results:
  - read:
      path: /core/transaction/v2/result/summary
      method: GET

transaction_topology_result:
  - read:
      path: /core/transaction/v2/result/topology/{transactionId}
      method: GET

user_storage_in_file_content:
  - create:
      path: /core/user-storage/v2/file
      method: POST
  - update:
      path: /core/user-storage/v2/file
      method: PUT
  - create:
      path: /core/user-storage/v2/shared/file
      method: POST
  - update:
      path: /core/user-storage/v2/shared/file
      method: PUT

user_storage_out_dir_content:
  - read:
      path: /core/user-storage/v2/directory
      method: GET
  - read:
      path: /core/user-storage/v2/shared/directory
      method: GET

user_storage_out_file_content:
  - read:
      path: /core/user-storage/v2/file
      method: GET
  - read:
      path: /core/user-storage/v2/shared/file
      method: GET

workflow_status_summary:
  - read:
      path: /core/workflows/v1
      method: GET

db_get_result:
  - read:
      path: /core/db/v1/{path}
      method: GET
  - read:
      path: /core/db/v2/data
      method: GET
  - read:
      path: /core/db/v2/schema
      method: GET

transaction_topology_request:
  - create:
      path: /core/transaction/v2/result/topology/{transactionId}
      method: POST

version_info:
  - read:
      path: /core/about/version
      method: GET

totalPaths: 81
totalSchemas: 154
usedSchemas: 59
unusedSchemas: 95
unusedSchemaList:
  - AccessQuery
  - AccessResult
  - AlarmHistoryData
  - AlarmTarget
  - AuthProvider_auth
  - AuthProvider_groupSupport
  - AutoCompleteDetails
  - AutoCompleteResponse
  - AutoCompletion
  - ChatResponseType
  - CheckAccessResponse
  - ConversationHistoryMessage
  - ConversationHistoryRole
  - CrAnnotation
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - GroupID
  - GroupVersionKind
  - GroupVersionResource
  - HealthServiceStatus
  - Identifier
  - K8SPatchOp
  - LabelCompletionResponse
  - LineSegment
  - Metadata
  - NamespaceData
  - NsCrGvkName
  - OperationType
  - OverlayState
  - Patch
  - ProviderAuth
  - QueryCompletion
  - QueryConvertResponse
  - ResourceRule
  - StoreAppRequirementsGraphItem
  - StoreAppRequirementsGraphItem_installedAppVersion
  - StoreAppRequirementsGraphItem_targetAppVersion
  - StoreAppVersion
  - StoreAppVersionMetadata
  - StoreAppVersionWithMetadata
  - TableRule
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoGroupingStateRequest
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayAttrMetadata
  - TopoOverlayAttrQuery
  - TopoOverlayBadgeMetadata
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayStateMetadata
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - TopologyGroupingInstance_metadata
  - TopologyStateGroupSelector
  - TopologyStateGroupingBase
  - TopologyStateTierSelector
  - TransactionAppError
  - TransactionContent
  - TransactionId
  - TransactionInputResource
  - TransactionIntentResult
  - TransactionNodeResult
  - TransactionNsCrGvkNames
  - TransactionPatch
  - TransactionResultObjectString
  - TransactionScriptResults
  - TransactionStructuredAppError
  - TransactionType
  - TransactionValue
  - UrlRule
  - UserStatus
  - UserStorageOutDirEntry
  - singleVersionInfo
