// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_user_storage_dir

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserStorageDirDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"base64encode": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "if true, file content will be base64-encoded before being returned",
				MarkdownDescription: "if true, file content will be base64-encoded before being returned",
			},
			"directorypath": schema.StringAttribute{
				Computed:            true,
				Description:         "path for the directory within the users storage",
				MarkdownDescription: "path for the directory within the users storage",
			},
			"entries": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"modificationtime": schema.StringAttribute{
							Computed:            true,
							Description:         "modification type of the item, if a file",
							MarkdownDescription: "modification type of the item, if a file",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "name of the item within the directory",
							MarkdownDescription: "name of the item within the directory",
						},
						"type": schema.StringAttribute{
							Computed:            true,
							Description:         "type of the item; \"file\" or \"directory\"",
							MarkdownDescription: "type of the item; \"file\" or \"directory\"",
						},
					},
					CustomType: EntriesType{
						ObjectType: types.ObjectType{
							AttrTypes: EntriesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "array of entries for the items in the directory",
				MarkdownDescription: "array of entries for the items in the directory",
			},
			"path": schema.StringAttribute{
				Required:            true,
				Description:         "path for the file/directory being manipulated",
				MarkdownDescription: "path for the file/directory being manipulated",
			},
		},
	}
}

type UserStorageDirModel struct {
	Base64encode  types.Bool   `tfsdk:"base64encode"`
	Directorypath types.String `tfsdk:"directorypath"`
	Entries       types.List   `tfsdk:"entries"`
	Path          types.String `tfsdk:"path"`
}

var _ basetypes.ObjectTypable = EntriesType{}

type EntriesType struct {
	basetypes.ObjectType
}

func (t EntriesType) Equal(o attr.Type) bool {
	other, ok := o.(EntriesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t EntriesType) String() string {
	return "EntriesType"
}

func (t EntriesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	modificationtimeAttribute, ok := attributes["modificationtime"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modificationtime is missing from object`)

		return nil, diags
	}

	modificationtimeVal, ok := modificationtimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modificationtime expected to be basetypes.StringValue, was: %T`, modificationtimeAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return EntriesValue{
		Modificationtime: modificationtimeVal,
		Name:             nameVal,
		EntriesType:      typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewEntriesValueNull() EntriesValue {
	return EntriesValue{
		state: attr.ValueStateNull,
	}
}

func NewEntriesValueUnknown() EntriesValue {
	return EntriesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewEntriesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (EntriesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing EntriesValue Attribute Value",
				"While creating a EntriesValue value, a missing attribute value was detected. "+
					"A EntriesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EntriesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid EntriesValue Attribute Type",
				"While creating a EntriesValue value, an invalid attribute value was detected. "+
					"A EntriesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EntriesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("EntriesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra EntriesValue Attribute Value",
				"While creating a EntriesValue value, an extra attribute value was detected. "+
					"A EntriesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra EntriesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewEntriesValueUnknown(), diags
	}

	modificationtimeAttribute, ok := attributes["modificationtime"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modificationtime is missing from object`)

		return NewEntriesValueUnknown(), diags
	}

	modificationtimeVal, ok := modificationtimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modificationtime expected to be basetypes.StringValue, was: %T`, modificationtimeAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewEntriesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewEntriesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewEntriesValueUnknown(), diags
	}

	return EntriesValue{
		Modificationtime: modificationtimeVal,
		Name:             nameVal,
		EntriesType:      typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewEntriesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) EntriesValue {
	object, diags := NewEntriesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewEntriesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t EntriesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewEntriesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewEntriesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewEntriesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewEntriesValueMust(EntriesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t EntriesType) ValueType(ctx context.Context) attr.Value {
	return EntriesValue{}
}

var _ basetypes.ObjectValuable = EntriesValue{}

type EntriesValue struct {
	Modificationtime basetypes.StringValue `tfsdk:"modificationtime"`
	Name             basetypes.StringValue `tfsdk:"name"`
	EntriesType      basetypes.StringValue `tfsdk:"type"`
	state            attr.ValueState
}

func (v EntriesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["modificationtime"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Modificationtime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["modificationtime"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.EntriesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v EntriesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v EntriesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v EntriesValue) String() string {
	return "EntriesValue"
}

func (v EntriesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"modificationtime": basetypes.StringType{},
		"name":             basetypes.StringType{},
		"type":             basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"modificationtime": v.Modificationtime,
			"name":             v.Name,
			"type":             v.EntriesType,
		})

	return objVal, diags
}

func (v EntriesValue) Equal(o attr.Value) bool {
	other, ok := o.(EntriesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Modificationtime.Equal(other.Modificationtime) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.EntriesType.Equal(other.EntriesType) {
		return false
	}

	return true
}

func (v EntriesValue) Type(ctx context.Context) attr.Type {
	return EntriesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v EntriesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"modificationtime": basetypes.StringType{},
		"name":             basetypes.StringType{},
		"type":             basetypes.StringType{},
	}
}
