// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_auth_user_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AuthUserGroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed: true,
			},
			"full_roles": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If true, the full definitions of the roles associated with the group\nare returned, rather than just the role names.",
				MarkdownDescription: "If true, the full definitions of the roles associated with the group\nare returned, rather than just the role names.",
			},
			"full_users": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If true, the full definitions of the users which are members of the group\nare returned, rather than just the user names.",
				MarkdownDescription: "If true, the full definitions of the users which are members of the group\nare returned, rather than just the user names.",
			},
			"fullroles": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Deprecated: If true, the full definitions of the roles associated with the group\nare returned, rather than just the role names.  Use fullUsers instead.  Ignored if fullUsers present.",
				MarkdownDescription: "Deprecated: If true, the full definitions of the roles associated with the group\nare returned, rather than just the role names.  Use fullUsers instead.  Ignored if fullUsers present.",
			},
			"fullusers": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Deprecated: If true, the full definitions of the users which are members of the group\nare returned, rather than just the user names.  Use fullRoles instead. Ignored if fullRoles present.",
				MarkdownDescription: "Deprecated: If true, the full definitions of the users which are members of the group\nare returned, rather than just the user names.  Use fullRoles instead. Ignored if fullRoles present.",
			},
			"is_federated": schema.BoolAttribute{
				Computed:            true,
				Description:         "if true, indicates that the group was imported from a federated LDAP server",
				MarkdownDescription: "if true, indicates that the group was imported from a federated LDAP server",
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"roles": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Contains the names of the ClusterRoles and Roles roles associated with the group.\nA Role name has the form \"namesspace:rolename\", whereas a ClusteRole name is a\nsimple \"rolename\", without a colon or a namespace.",
				MarkdownDescription: "Contains the names of the ClusterRoles and Roles roles associated with the group.\nA Role name has the form \"namesspace:rolename\", whereas a ClusteRole name is a\nsimple \"rolename\", without a colon or a namespace.",
			},
			"users": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "contains the usernames of the users who are members of the group",
				MarkdownDescription: "contains the usernames of the users who are members of the group",
			},
			"uuid": schema.StringAttribute{
				Required:            true,
				Description:         "The UUID of the EDA user group whose definition should be retrieved.",
				MarkdownDescription: "The UUID of the EDA user group whose definition should be retrieved.",
			},
		},
	}
}

type AuthUserGroupModel struct {
	Description types.String `tfsdk:"description"`
	FullRoles   types.Bool   `tfsdk:"full_roles"`
	FullUsers   types.Bool   `tfsdk:"full_users"`
	Fullroles   types.Bool   `tfsdk:"fullroles"`
	Fullusers   types.Bool   `tfsdk:"fullusers"`
	IsFederated types.Bool   `tfsdk:"is_federated"`
	Name        types.String `tfsdk:"name"`
	Roles       types.List   `tfsdk:"roles"`
	Users       types.List   `tfsdk:"users"`
	Uuid        types.String `tfsdk:"uuid"`
}
