// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_db_get_schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DbGetSchemaDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"remove_read_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "whether to remove read only fields from the schema",
				MarkdownDescription: "whether to remove read only fields from the schema",
			},
			"table_name": schema.StringAttribute{
				Required:            true,
				Description:         "the name of the table to retrieve the schema from the database",
				MarkdownDescription: "the name of the table to retrieve the schema from the database",
			},
		},
	}
}

type DbGetSchemaModel struct {
	RemoveReadOnly types.Bool   `tfsdk:"remove_read_only"`
	TableName      types.String `tfsdk:"table_name"`
}
