// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_user_storage_shared_file

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserStorageSharedFileDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"base64encode": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "if true, file content will be base64-encoded before being returned",
				MarkdownDescription: "if true, file content will be base64-encoded before being returned",
			},
			"filecontent": schema.StringAttribute{
				Computed:            true,
				Description:         "content of the file, will be base64 encoded if the request asked for this",
				MarkdownDescription: "content of the file, will be base64 encoded if the request asked for this",
			},
			"filedeleted": schema.BoolAttribute{
				Computed:            true,
				Description:         "if present and true, indicates the file has been deleted; used for\nstreamed responses",
				MarkdownDescription: "if present and true, indicates the file has been deleted; used for\nstreamed responses",
			},
			"filename": schema.StringAttribute{
				Computed:            true,
				Description:         "name of the file",
				MarkdownDescription: "name of the file",
			},
			"modificationtime": schema.StringAttribute{
				Computed:            true,
				Description:         "UTC modification time of the file, as an RFC 3339 date/time.\nNot valid if file-deleted is true (in a streamed response)",
				MarkdownDescription: "UTC modification time of the file, as an RFC 3339 date/time.\nNot valid if file-deleted is true (in a streamed response)",
			},
			"path": schema.StringAttribute{
				Required:            true,
				Description:         "path for the file/directory being manipulated",
				MarkdownDescription: "path for the file/directory being manipulated",
			},
		},
	}
}

type UserStorageSharedFileModel struct {
	Base64encode     types.Bool   `tfsdk:"base64encode"`
	Filecontent      types.String `tfsdk:"filecontent"`
	Filedeleted      types.Bool   `tfsdk:"filedeleted"`
	Filename         types.String `tfsdk:"filename"`
	Modificationtime types.String `tfsdk:"modificationtime"`
	Path             types.String `tfsdk:"path"`
}
