provider:
  name: core

data_sources:
  alarm:
    read:
      path: /core/alarm/v2/namespaces/{nsName}/alarms/{alarm-name}
      method: GET

  alarms:
    read:
      path: /core/alarm/v2/namespaces/{nsName}/alarms
      method: GET
      
  cluster_alarm:
    read:
      path: /core/alarm/v2/alarms/{alarm-name}
      method: GET

  cluster_alarms:
    read:
      path: /core/alarm/v2/alarms
      method: GET

  alarm_history:
    read:
      path: /core/alarm/v2/namespaces/{nsName}/alarms/{alarm-name}/history
      method: GET

  cluster_alarm_history:
    read:
      path: /core/alarm/v2/alarms/{alarm-name}/history
      method: GET

  auth_password_policy:
    read:
      path: /core/admin/passwordpolicy
      method: GET

  auth_provider:
    read:
      path: "/core/admin/federationproviders/{uuid}"
      method: GET

  auth_providers:
    read:
      path: /core/admin/federationproviders
      method: GET

  auth_role:
    read:
      path: /core/admin/namespaces/{namespace}/roles/{name}
      method: GET

  auth_roles:
    read:
      path: /core/admin/namespaces/{namespace}/roles
      method: GET

  cluster_auth_role:
    read:
      path: "/core/admin/roles/{name}"
      method: GET

  cluster_auth_roles:
    read:
      path: /core/admin/roles
      method: GET

  auth_user:
    read:
      path: "/core/admin/users/{uuid}"
      method: GET

  auth_users:
    read:
      path: "/core/admin/users"
      method: GET

  auth_user_group:
    read:
      path: "/core/admin/groups/{uuid}"
      method: GET

  auth_user_groups:
    read:
      path: /core/admin/groups
      method: GET

  group_roles:
    read:
      path: /core/admin/groups/{uuid}/roles
      method: GET

  health:
    read:
      path: /core/about/health
      method: GET

  namespace_get_response:
    read:
      path: "/core/access/v1/namespaces"
      method: GET

  node_config_response:
    read:
      path: /core/nodeconfig/v2/namespaces/{nsName}/nodes/{nodeName}
      method: GET

  stream_result:
    read:
      path: /core/query/v1
      method: GET

  eql_stream_result:
    read:
      path: /core/query/v1/eql
      method: GET

  nql_stream_result:
    read:
      path: /core/query/v1/nql
      method: GET

  overlay:
    read:
      path: /core/topology/v1/{topologyName}/overlay/{overlayName}
      method: GET

  overlays:
    read:
      path: /core/topology/v1/{topologyName}/overlay
      method: GET

  query_completion_response:
    read:
      path: /core/query/v1/eql/autocomplete
      method: GET

  store_app_installed_settings:
    read:
      path: /core/store/v1/installedsettings/app/{appId}
      method: GET

  store_app_manifest:
    read:
      path: /core/store/v1/manifest/catalog/{catalog}/app/{appId}
      method: GET

  store_app_requirements_graph:
    read:
      path: /core/store/v1/requirementsgraph/catalog/{catalog}/app/{appId}
      method: GET

  store_app_summary_list:
    read:
      path: /core/store/v1/appsummaries
      method: GET

  store_app_version_list:
    read:
      path: /core/store/v1/versions/app/{appId}
      method: GET

  store_category_list:
    read:
      path: /core/store/v1/categories
      method: GET

  topology:
    read:
      path: /core/topology/v1/{topologyName}
      method: GET

  topologies:
    read:
      path: /core/topology/v1
      method: GET

  transaction_node_config_diff:
    read:
      path: /core/transaction/v2/result/diffs/nodecfg/{transactionId}
      method: GET

  transaction_resource_diff:
    read:
      path: /core/transaction/v2/result/diffs/resource/{transactionId}
      method: GET

  transaction_execution_result:
    read:
      path: /core/transaction/v2/result/execution/{transactionId}
      method: GET

  transaction_input_resource:
    read:
      path: /core/transaction/v2/result/inputresources/{transactionId}
      method: GET

  transaction_result_summary:
    read:
      path: /core/transaction/v2/result/summary/{transactionId}
      method: GET

  transaction_result_summaries:
    read:
      path: /core/transaction/v2/result/summary
      method: GET

  transaction_state:
    read:
      path: /core/transaction/v2/state/{transactionId}
      method: GET

  user_storage_dir:
    read:
      path: /core/user-storage/v2/directory
      method: GET

  user_storage_shared_dir:
    read:
      path: /core/user-storage/v2/shared/directory
      method: GET

  user_storage_file:
    read:
      path: /core/user-storage/v2/file
      method: GET

  user_storage_shared_file:
    read:
      path: /core/user-storage/v2/shared/file
      method: GET

  workflow:
    read:
      path: /core/workflow/v1/workflow/{workflowId}
      method: GET

  workflow_list:
    read:
      path: /core/workflow/v1/{nsName}/list
      method: GET

  cluster_workflow_list:
    read:
      path: /core/workflow/v1/list
      method: GET

  workflow_detail:
    read:
      path: /core/workflow/v1/details/{workflowId}
      method: GET

  workflow_state:
    read:
      path: /core/workflow/v1/state/{workflowId}
      method: GET

resources:
  auth_provider:
    create:
      path: /core/admin/federationproviders
      method: POST
    read:
      path: /core/admin/federationproviders/{uuid}
      method: GET
    update:
      path: /core/admin/federationproviders/{uuid}
      method: PUT
    delete:
      path: /core/admin/federationproviders/{uuid}
      method: DELETE

  auth_role:
    create:
      path: /core/admin/namespaces/{namespace}/roles
      method: POST
    read:
      path: /core/admin/namespaces/{namespace}/roles/{name}
      method: GET
    update:
      path: /core/admin/namespaces/{namespace}/roles/{name}
      method: PUT
    delete:
      path: /core/admin/namespaces/{namespace}/roles/{name}
      method: DELETE

  cluster_auth_role:
    create:
      path: /core/admin/roles
      method: POST
    read:
      path: /core/admin/roles/{name}
      method: GET
    update:
      path: /core/admin/roles/{name}
      method: PUT
    delete:
      path: /core/admin/roles/{name}
      method: DELETE

  auth_user:
    create:
      path: /core/admin/users
      method: POST
    read:
      path: /core/admin/users/{uuid}
      method: GET
    update:
      path: /core/admin/users/{uuid}
      method: PUT
    delete:
      path: /core/admin/users/{uuid}
      method: DELETE

  auth_user_group:
    create:
      path: /core/admin/groups
      method: POST
    read:
      path: /core/admin/groups/{uuid}
      method: GET
    update:
      path: /core/admin/groups/{uuid}
      method: PUT
    delete:
      path: /core/admin/groups/{uuid}
      method: DELETE

  # group_role:
  #   create:
  #     path: /core/admin/groups/{uuid}/roles
  #     method: POST
  #   read:
  #     path: /core/admin/groups/{uuid}/roles
  #     method: GET
  #   update:
  #     path: /core/admin/groups/{uuid}/roles
  #     method: PUT
  #   delete:
  #     path: /core/admin/groups/{uuid}/roles
  #     method: DELETE

  # transaction:
  #   create:
  #     path: /core/transaction/v2
  #     method: POST
  #   read:
  #     path: /core/transaction/v2
  #     method: GET

  # user_storage_file:
  #   create:
  #     path: /core/user-storage/v2/file
  #     method: POST
  #   read:
  #     path: /core/user-storage/v2/file
  #     method: GET
  #   update:
  #     path: /core/user-storage/v2/file
  #     method: PUT
  #   delete:
  #     path: /core/user-storage/v2/file
  #     method: DELETE

  # user_storage_shared_file:
  #   create:
  #     path: /core/user-storage/v2/shared/file
  #     method: POST
  #   read:
  #     path: /core/user-storage/v2/shared/file
  #     method: GET
  #   update:
  #     path: /core/user-storage/v2/shared/file
  #     method: PUT
  #   delete:
  #     path: /core/user-storage/v2/shared/file
  #     method: DELETE

  workflow:
    create:
      path: /core/workflow/v1
      method: POST
    read:
      path: /core/workflow/v1/workflow/{workflowId}
      method: GET
