// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_group_member_user_ids

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func GroupMemberUserIdsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"group_member_user_ids": schema.SetAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"uuid": schema.StringAttribute{
				Required:            true,
				Description:         "The UUID of the EDA user group whose members should be listed.",
				MarkdownDescription: "The UUID of the EDA user group whose members should be listed.",
			},
		},
	}
}

type GroupMemberUserIdsModel struct {
	GroupMemberUserIds types.Set    `tfsdk:"group_member_user_ids"`
	Uuid               types.String `tfsdk:"uuid"`
}
