// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_branch_diff_response

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BranchDiffResponseDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"after": schema.StringAttribute{
				Computed:            true,
				Description:         "After is the YAML form of the CR's current state (empty string for deletes).",
				MarkdownDescription: "After is the YAML form of the CR's current state (empty string for deletes).",
			},
			"before": schema.StringAttribute{
				Computed:            true,
				Description:         "Before is the YAML form of the CR's prior state (empty string if there was no prior state).",
				MarkdownDescription: "Before is the YAML form of the CR's prior state (empty string if there was no prior state).",
			},
			"group": schema.StringAttribute{
				Required:            true,
				Description:         "Group for the resource diff.",
				MarkdownDescription: "Group for the resource diff.",
			},
			"hash": schema.StringAttribute{
				Required:            true,
				Description:         "Branch head hash; response is only returned if this matches the current branch state.",
				MarkdownDescription: "Branch head hash; response is only returned if this matches the current branch state.",
			},
			"kind": schema.StringAttribute{
				Required:            true,
				Description:         "Kind for the resource diff.",
				MarkdownDescription: "Kind for the resource diff.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name for the resource diff.",
				MarkdownDescription: "Name for the resource diff.",
			},
			"namespace": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Namespace for the resource diff. Required if the resource is namespaced.",
				MarkdownDescription: "Namespace for the resource diff. Required if the resource is namespaced.",
			},
			"version": schema.StringAttribute{
				Required:            true,
				Description:         "Version for the resource diff.",
				MarkdownDescription: "Version for the resource diff.",
			},
		},
	}
}

type BranchDiffResponseModel struct {
	After     types.String `tfsdk:"after"`
	Before    types.String `tfsdk:"before"`
	Group     types.String `tfsdk:"group"`
	Hash      types.String `tfsdk:"hash"`
	Kind      types.String `tfsdk:"kind"`
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Version   types.String `tfsdk:"version"`
}
