// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_conversation_list

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ConversationListDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"conversation_list": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created": schema.StringAttribute{
							Computed:            true,
							Description:         "Time when the conversation was created",
							MarkdownDescription: "Time when the conversation was created",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "Conversation ID",
							MarkdownDescription: "Conversation ID",
						},
						"last_updated": schema.StringAttribute{
							Computed:            true,
							Description:         "Time when the conversation was last updated",
							MarkdownDescription: "Time when the conversation was last updated",
						},
						"message_count": schema.Int64Attribute{
							Computed:            true,
							Description:         "Number of messages in the conversation",
							MarkdownDescription: "Number of messages in the conversation",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Conversation name",
							MarkdownDescription: "Conversation name",
						},
					},
					CustomType: ConversationListType{
						ObjectType: types.ObjectType{
							AttrTypes: ConversationListValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type ConversationListModel struct {
	ConversationList types.Set `tfsdk:"conversation_list"`
}

var _ basetypes.ObjectTypable = ConversationListType{}

type ConversationListType struct {
	basetypes.ObjectType
}

func (t ConversationListType) Equal(o attr.Type) bool {
	other, ok := o.(ConversationListType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConversationListType) String() string {
	return "ConversationListType"
}

func (t ConversationListType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return nil, diags
	}

	createdVal, ok := createdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.StringValue, was: %T`, createdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUpdatedAttribute, ok := attributes["last_updated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_updated is missing from object`)

		return nil, diags
	}

	lastUpdatedVal, ok := lastUpdatedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_updated expected to be basetypes.StringValue, was: %T`, lastUpdatedAttribute))
	}

	messageCountAttribute, ok := attributes["message_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message_count is missing from object`)

		return nil, diags
	}

	messageCountVal, ok := messageCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message_count expected to be basetypes.Int64Value, was: %T`, messageCountAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConversationListValue{
		Created:      createdVal,
		Id:           idVal,
		LastUpdated:  lastUpdatedVal,
		MessageCount: messageCountVal,
		Name:         nameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewConversationListValueNull() ConversationListValue {
	return ConversationListValue{
		state: attr.ValueStateNull,
	}
}

func NewConversationListValueUnknown() ConversationListValue {
	return ConversationListValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConversationListValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConversationListValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConversationListValue Attribute Value",
				"While creating a ConversationListValue value, a missing attribute value was detected. "+
					"A ConversationListValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConversationListValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConversationListValue Attribute Type",
				"While creating a ConversationListValue value, an invalid attribute value was detected. "+
					"A ConversationListValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConversationListValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConversationListValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConversationListValue Attribute Value",
				"While creating a ConversationListValue value, an extra attribute value was detected. "+
					"A ConversationListValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConversationListValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConversationListValueUnknown(), diags
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return NewConversationListValueUnknown(), diags
	}

	createdVal, ok := createdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.StringValue, was: %T`, createdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewConversationListValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUpdatedAttribute, ok := attributes["last_updated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_updated is missing from object`)

		return NewConversationListValueUnknown(), diags
	}

	lastUpdatedVal, ok := lastUpdatedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_updated expected to be basetypes.StringValue, was: %T`, lastUpdatedAttribute))
	}

	messageCountAttribute, ok := attributes["message_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message_count is missing from object`)

		return NewConversationListValueUnknown(), diags
	}

	messageCountVal, ok := messageCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message_count expected to be basetypes.Int64Value, was: %T`, messageCountAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewConversationListValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewConversationListValueUnknown(), diags
	}

	return ConversationListValue{
		Created:      createdVal,
		Id:           idVal,
		LastUpdated:  lastUpdatedVal,
		MessageCount: messageCountVal,
		Name:         nameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewConversationListValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConversationListValue {
	object, diags := NewConversationListValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConversationListValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConversationListType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConversationListValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConversationListValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConversationListValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConversationListValueMust(ConversationListValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConversationListType) ValueType(ctx context.Context) attr.Value {
	return ConversationListValue{}
}

var _ basetypes.ObjectValuable = ConversationListValue{}

type ConversationListValue struct {
	Created      basetypes.StringValue `tfsdk:"created"`
	Id           basetypes.StringValue `tfsdk:"id"`
	LastUpdated  basetypes.StringValue `tfsdk:"last_updated"`
	MessageCount basetypes.Int64Value  `tfsdk:"message_count"`
	Name         basetypes.StringValue `tfsdk:"name"`
	state        attr.ValueState
}

func (v ConversationListValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["created"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_updated"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["message_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Created.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.LastUpdated.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_updated"] = val

		val, err = v.MessageCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message_count"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConversationListValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConversationListValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConversationListValue) String() string {
	return "ConversationListValue"
}

func (v ConversationListValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created":       basetypes.StringType{},
		"id":            basetypes.StringType{},
		"last_updated":  basetypes.StringType{},
		"message_count": basetypes.Int64Type{},
		"name":          basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created":       v.Created,
			"id":            v.Id,
			"last_updated":  v.LastUpdated,
			"message_count": v.MessageCount,
			"name":          v.Name,
		})

	return objVal, diags
}

func (v ConversationListValue) Equal(o attr.Value) bool {
	other, ok := o.(ConversationListValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Created.Equal(other.Created) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.LastUpdated.Equal(other.LastUpdated) {
		return false
	}

	if !v.MessageCount.Equal(other.MessageCount) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v ConversationListValue) Type(ctx context.Context) attr.Type {
	return ConversationListType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConversationListValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created":       basetypes.StringType{},
		"id":            basetypes.StringType{},
		"last_updated":  basetypes.StringType{},
		"message_count": basetypes.Int64Type{},
		"name":          basetypes.StringType{},
	}
}
